### ISSUE TITLE
Cluster Set --> Submariner add-ons --> view documentation shows 404 error

### ISSUE THREAD

**Issue by sridhargaddam** [open-cluster-management/submariner-addon#132]
Link to Submariner add-on managed cluster documentation is broken 
Cluster Set --> Submariner add-ons --> view documentation results in 404 error

**Comment by Jaanki** [comment]
/project https://github.com/orgs/open-cluster-management/projects/1

**Comment by Jaanki** [comment]
https://github.com/open-cluster-management/console/pull/842

**Comment by Jaanki** [comment]
Depends on https://github.com/open-cluster-management/console/pull/891

**Comment by Jaanki** [comment]
Issue to track fix to 2.3 https://github.com/open-cluster-management/backlog/issues/16741
