### ISSUE TITLE
A connection between the clusters is not working with kind deployment

### ISSUE THREAD

**Issue by MaxBab** [open-cluster-management/submariner-addon#22]
After a deployment of a test environment with kind, the connection between the clusters is not working.
A test deployment has an errors on submariner-operator pod:

{"level":"error","ts":1606133404.3297968,"logger":"controller_submariner","msg":"failed to update the Submariner status","Request.Namespace":"submariner-operator","Request.Name":"submariner","error":"Submariner.submariner.io \"submariner\" is invalid: [status.engineDaemonSetStatus.currentNumberScheduled: Required value, status.engineDaemonSetStatus.desiredNumberScheduled: Required value, status.engineDaemonSetStatus.numberMisscheduled: Required value, status.engineDaemonSetStatus.numberReady: Required value, status.routeAgentDaemonSetStatus.currentNumberScheduled: Required value, status.routeAgentDaemonSetStatus.desiredNumberScheduled: Required value, status.routeAgentDaemonSetStatus.numberMisscheduled: Required value, status.routeAgentDaemonSetStatus.numberReady: Required value, status.globalnetDaemonSetStatus.currentNumberScheduled: Required value, status.globalnetDaemonSetStatus.desiredNumberScheduled: Required value, status.globalnetDaemonSetStatus.numberMisscheduled: Required value, status.globalnetDaemonSetStatus.numberReady: Required value]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tsubmariner-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/submariner-io/submariner-operator/pkg/controller/submariner.(*ReconcileSubmariner).Reconcile\n\tsubmariner-operator/pkg/controller/submariner/submariner_controller.go:250\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsubmariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsubmariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsubmariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:201\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tsubmariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tsubmariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tsubmariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1606133404.3300195,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"submariner-controller","name":"submariner","namespace":"submariner-operator","error":"Submariner.submariner.io \"submariner\" is invalid: [status.engineDaemonSetStatus.currentNumberScheduled: Required value, status.engineDaemonSetStatus.desiredNumberScheduled: Required value, status.engineDaemonSetStatus.numberMisscheduled: Required value, status.engineDaemonSetStatus.numberReady: Required value, status.routeAgentDaemonSetStatus.currentNumberScheduled: Required value, status.routeAgentDaemonSetStatus.desiredNumberScheduled: Required value, status.routeAgentDaemonSetStatus.numberMisscheduled: Required value, status.routeAgentDaemonSetStatus.numberReady: Required value, status.globalnetDaemonSetStatus.currentNumberScheduled: Required value, status.globalnetDaemonSetStatus.desiredNumberScheduled: Required value, status.globalnetDaemonSetStatus.numberMisscheduled: Required value, status.globalnetDaemonSetStatus.numberReady: Required value]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tsubmariner-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsubmariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:248\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsubmariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsubmariner-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:201\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tsubmariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tsubmariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tsubmariner-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

**Comment by MaxBab** [comment]
Have the following message in the multiclusterservices.lighthouse.submariner.io crd


  Conditions:
    Last Transition Time:  2020-11-23T10:26:25Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2020-11-23T10:26:25Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
    Last Transition Time:  2020-11-23T10:31:25Z
    Message:               [spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[clusterServiceInfo].type: Required value: must not be empty for specified object fields, spec.versions[0].schema.openAPIV3Schema.properties[spec].type: Required value: must not be empty for specified object fields, spec.versions[0].schema.openAPIV3Schema.type: Required value: must not be empty at the root]
    Reason:                Violations
    Status:                True
    Type:                  NonStructuralSchema

**Comment by dfarrell07** [comment]
Per discussing a bit with @MaxBab on Slack, my suggestion is to consider building on/integrating Submariner's existing tooling to make maintenance/integration easier. We'd be glad to help with that.

**Comment by skeeey** [comment]
The crd problem should be fixed, close this
