### ISSUE TITLE
[Question] How to enable globalnet feature when there are overlapping CIDRs in connecting clusters

### ISSUE THREAD

**Issue by SataQiu** [open-cluster-management/submariner-addon#223]
How to enable [globalnet](https://submariner.io/getting-started/architecture/globalnet/) feature when there are overlapping CIDRs in connecting clusters?

Is there an option to control this feature? 
Where can I find more information about configuring `globalnet` in `submariner-addon`?

Looking forward to reply!

**Comment by sridhargaddam** [comment]
> How to enable [globalnet](https://submariner.io/getting-started/architecture/globalnet/) feature when there are overlapping CIDRs in connecting clusters?
If you are using `subctl` to installing Submariner, you can enable `globlanet` by simply specifying the flag `--globalnet` while deploying the broker. For example

```
subctl deploy-broker  --kubeconfig cluster-a/auth/kubeconfig --globalnet
subctl join --kubeconfig cluster-a/auth/kubeconfig broker-info.subm --clusterid cluster-a
subctl join --kubeconfig cluster-b/auth/kubeconfig broker-info.subm --clusterid cluster-b
```

> Is there an option to control this feature? Where can I find more information about configuring `globalnet` in `submariner-addon`?

Currently `globanet` is not supported with submariner-addon and we are actively working on adding this feature in the upcoming release. The following EPIC is used to track the feature support - https://github.com/submariner-io/enhancements/issues/51
