### ISSUE TITLE
ACM setup fails to resolve DNS queries with NODATA results

### ISSUE THREAD

**Issue by giannisalinetti** [open-cluster-management/submariner-addon#28]
### Description
When the submariner-addon is installed on a RHACM with one hub and two managed clusters DNS resolution fails with NODATA results thus preventing correct communication among services.

#### Hub Cluster
- Cluster name: local-cluster
- OCP version: 4.6.4
- RHACM version: 2.1
- Provider: AWS
- Control plane: 3x m5.xlarge
- Worker nodes: 3x m5.xlarge
- Installation method: IPI
- Networking: OpenShiftSDN
- Service Network: 172.30.0.0/16

##### Managed Cluster 1
- Cluster name: demo-cluster-01
- OCP version: 4.6.4
- Provider: AWS
- Control plane: 3x m5.xlarge
- Worker nodes: 3x m5.large
- Installation method: IPI
- Networking: OpenShiftSDN
- Service Network: 172.31.0.0/16

##### Managed Cluster 2
- Cluster name: demo-cluster-02
- OCP version: 4.6.4
- Provider: AWS
- Control plane: 3x m5.xlarge
- Worker nodes: 3x m5.large
- Installation method: IPI
- Networking: OpenShiftSDN
- Service Network: 172.32.0.0/16

### Steps to reproduce
1. Install RHACM operator and create MulticlusterHub resource. 
2. Join the managed clusters using the generated command from the RHACM web console
3. Wait for the clusters to be correctly joined:
   ```
   $ oc get managedclusters
   NAME              HUB ACCEPTED   MANAGED CLUSTER URLS   JOINED   AVAILABLE   AGE  
   demo-cluster-01   true                                  True     True        2d12h
   demo-cluster-02   true                                  True     True        2d12h
   local-cluster     true                                  True     True        3d7h
   ```
4. Apply the submanriner manifest addon using kustomize and the resources provided in this repo
   ```
   $ oc apply -k deploy/config/manifests
   ```
5. Wait for the submariner addon componentes to be deployed on both clusters
6. Inspect correct DNS forwarding on the managed nodes
   ```
   $ oc get dnses.operator.openshift.io/default -o jsonpath='{.spec.servers[]}'
   map[forwardPlugin:map[upstreams:[172.31.92.81]] name:lighthouse zones:[clusterset.local]]

   $ oc get dnses.operator.openshift.io/default -o jsonpath='{.spec.servers[]}'
   map[forwardPlugin:map[upstreams:[172.32.169.237]] name:lighthouse zones:[clusterset.local]]
   ```
7. Create a ManagedClusterSet on the hub cluster
   ```
   cat << EOF | kubectl apply -f
   apiVersion: cluster.open-cluster-management.io/v1alpha1
   kind: ManagedClusterSet
   metadata:
     name: pro
   ```
8. Enable Submariner on the managed clusters
   ```
   $ oc label managedclusters <managedcluster name> "cluster.open-cluster-management.io/submariner-agent=true" --overwrite
   ```
9. Join the managed clusters to the ManagedClusterSet
   ```
   $ oc label managedclusters <managedcluster name> "cluster.open-cluster-management.io/submariner-agent=true" --overwrite
   ```
10. Create a test application on **demo-cluster-02**:
   ```
   kubectl -n default create deployment nginx --image=nginx
   kubectl -n default expose deployment nginx --port=80
   kubectl -n default get svc nginx
   ```
11. Export the application service on **demo-cluster-02**:
   ```
   cat << EOF | kubectl -n default apply -f -
   apiVersion: lighthouse.submariner.io/v2alpha1
   kind: ServiceExport
   metadata:
     name: nginx
     namespace: default
   EOF
   ```
12. Wait for the creation of the associated ServiceImport on the ManagedClusterSet:
   ```
   $ kubectl get serviceimports.lighthouse.submariner.io --all-namespaces
   NAMESPACE                          NAME                                  AGE
   submariner-clusterset-pro-broker   nginx-default-demo-cluster-02         10h
   ```
13. Install a dnstools pod to test connectivity on **demo-cluster-01**
   ```
   cat <<EOF | kubectl apply -f -
   apiVersion: v1
   kind: Pod
   metadata:
     name: dnstools
     labels:
       app: dnstools
   spec:
     containers:
     - name: dnstools
       image: infoblox/dnstools:latest
       command: ["/bin/sleep", "3650d"]
   EOF
   ```
14. Test the name resolution
   ```
   $ kubectl exec -it dnstools -- dig nginx.default.svc.clusterset.local
   ```
### Expected results
The dig command should return NOERROR from the queried DNS (lighthouse) and a non-empty set of A records.

### Actual results
The dig command returns NOERROR with an empty set of records (witch is the way for dig to return NODATA)
```
$ kubectl exec -it dnstools -- dig A nginx.default.svc.clusterset.local

; <<>> DiG 9.11.3 <<>> A nginx.default.svc.clusterset.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44834
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 30b5d7ca2e073162 (echoed)
;; QUESTION SECTION:
;nginx.default.svc.clusterset.local. IN	A

;; Query time: 3 msec
;; SERVER: 172.31.0.10#53(172.31.0.10)
;; WHEN: Sun Dec 13 00:44:09 UTC 2020
;; MSG SIZE  rcvd: 75
```

Notice that the query is conducted to the default cluster DNS service (`dns-default`), whose endpoints are the CoreDNS pods running on each node.

### Additional considerations
The DNS requests looks correctly forwarded to the submariner-lighthouse-coredns pods. To verify this, simply query an NXDOMAIN (ie a non exported service) and the submariner-lighthouse-coredns pods will print logs similar to this:
```
[ERROR] plugin/errors: 3 nxdomain.default.svc.clusterset.local. A: plugin/lighthouse: record not found
```

This is enough to assume that the traffic is correctly forwarded from the clusters CoreDNS pods to the lighthouse CoreDNS pods.

The same results are produced by calling the lighthouse-coredns service directly:
```
$ kubectl exec -it dnstools -- dig @$(oc get svc/submariner-lighthouse-coredns -n submariner-operator -o jsonpath={.spec.clusterIP}) nginx.default.svc.clusterset.local
; <<>> DiG 9.11.3 <<>> @172.31.92.81 nginx.default.svc.clusterset.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61178
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 55d541eabac4035d (echoed)
;; QUESTION SECTION:
;nginx.default.svc.clusterset.local. IN	A

;; Query time: 0 msec
;; SERVER: 172.31.92.81#53(172.31.92.81)
;; WHEN: Sun Dec 13 00:59:24 UTC 2020
;; MSG SIZE  rcvd: 75
```

This demonstrates that the issue should not be related to DNS forwarding.

**Comment by zhiweiyin318** [comment]
@giannisalinetti  did you setup the gateway node for the 2 managed clusters?  please refer to https://submariner.io/getting-started/quickstart/openshift/aws/#prepare-aws-clusters-for-submariner if not.
we have changed a lot for submariner-addon in this release,  sorry for not updating the doc in time. the updated doc is coming soon.

**Comment by skeeey** [comment]
The doc has been updated, if there is any problems, please reopen this
