### ISSUE TITLE
Upgrade to controller-runtime 0.11.0 or later

### ISSUE THREAD

**Issue by skitt** [open-cluster-management/submariner-addon#281]
We need to upgrade our controller-runtime dependency.

Depends on https://github.com/kubernetes-sigs/controller-runtime/issues/1799

**Comment by nyechiel** [comment]
@skitt I am reviewing addon issues and came across this one. Is it still relevant?

**Comment by skitt** [comment]
Yes, we’re still on 0.9.1.
