### ISSUE TITLE
Finish upgrading to Submariner 0.12

### ISSUE THREAD

**Issue by skitt** [open-cluster-management/submariner-addon#332]
The code dependencies have been handled, but we still need to bump the dependency:

- [ ] in `pkg/hub/submarineragent/manifests/operator/submariner.io-submariners-cr.yaml` (the repository also needs to be changed to `registry.redhat.io/rhacm2`)
- [ ] `submver` in `scripts/deploy.sh`

**Comment by MaxBab** [comment]
@skitt 
For some reason, the issue was not closed after the patch merged.
Could be closed now.
